# A brief summary of NumPy
<br>
<div style="opacity: 0.8; font-family: Consolas, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New; font-size: 12px; font-style: italic;">
    ────────
    for more from the author, visit
    <a href="https://github.com/hazemanwer2000">github.com/hazemanwer2000</a>.
    ────────
</div>

## Table of Contents
* [Indexing](#indexing)
* [Operations](#operations)
  * [Custom Operations](#custom-operations)
* [Transformations](#transformations)


NumPy is a python package that provides and facilitates efficient manipulation of N-dimensional arrays.

In [2]:
import numpy as np

In [ ]:
# 1-Dimensional Array
np.array([1, 2, 3], dtype=int)

array([1, 2, 3])

In [ ]:
# 2-Dimensional Array
np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Shape = (Rows, Columns)
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
np.shape(a)

(2, 3)

## Indexing <a class="anchor" id="indexing"></a>

In [ ]:
# Access element
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
a[0, 1]

np.int64(2)

In [ ]:
# Access row
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
a[1, :]

array([4, 5, 6])

In [ ]:
# Access column
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
a[:, 1]

array([2, 5, 8])

In [60]:
# Slicing
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
a[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [5]:
# Slicing (with Selection)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
a[:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

## Operations <a class="anchor" id="operations"></a>

In [ ]:
# Operation(s) between array(s), of the same shape, are element-wise
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
b = np.ones(shape=np.shape(a), dtype=int)
a + b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
# Operation(s) between an array and an element, are supported 
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
a + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
# Operation(s) between (1-Dimensional) row(s) and 2-Dimensional array(s), are supported 
a = np.ones(shape=(3, 3), dtype=int)
row = np.array([[1, -1, 1]], dtype=int)
a + row

array([[2, 0, 2],
       [2, 0, 2],
       [2, 0, 2]])

In [61]:
# Operation(s) between (1-Dimensional) column(s) and 2-Dimensional array(s), are supported 
a = np.ones(shape=(3, 3), dtype=int)
column = np.array([[1], [-1], [1]], dtype=int)
a + column

array([[2, 2, 2],
       [0, 0, 0],
       [2, 2, 2]])

### Custom Operations <a class="anchor" id="custom-operations"></a>

In [64]:
# Between 2 N-Dimensional arrays, of the same shape
a = np.array(["A", "B", "C"], dtype=object)
b = np.array(["a", "b", "c"], dtype=object)
np.vectorize(lambda x, y: x + '=' + y, otypes=[object])(a, b)

array(['A=a', 'B=b', 'C=c'], dtype=object)

In [71]:
# Between N-Dimensional array, and element
a = np.array([["A", "B"], ["C", "D"]], dtype=object)
np.vectorize(lambda x, y: x + y, otypes=[object])(a, '()')

array([['A()', 'B()'],
       ['C()', 'D()']], dtype=object)

In [68]:
# Between N-Dimensional array, and row
a = np.array([["A", "B"], ["C", "D"]], dtype=object)
b = np.array([["1", "2"]], dtype=object)
np.vectorize(lambda x, y: x + y, otypes=[object])(a, b)

array([['A1', 'B2'],
       ['C1', 'D2']], dtype=object)

In [69]:
# Between N-Dimensional array, and column
a = np.array([["A", "B"], ["C", "D"]], dtype=object)
b = np.array([["1"], ["2"]], dtype=object)
np.vectorize(lambda x, y: x + y, otypes=[object])(a, b)

array([['A1', 'B1'],
       ['C2', 'D2']], dtype=object)

## Transformations <a class="anchor" id="transformations"></a>

In [72]:
# Transform 2-Dimensional array into (new) 2-Dimensional array
a = np.array([["A", "B", "C"], ["D", "E", "F"]], dtype=object)
np.vectorize(lambda x: x.lower(), otypes=[object])(a)

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype=object)

In [62]:
# Transform 2-Dimensional array into 1-Dimensional array (i.e., row into element)
a = np.array([["A", "B", "C"], ["D", "E", "F"]], dtype=object)
np.array([''.join(row) for row in a], dtype=object)

array(['ABC', 'DEF'], dtype=object)

In [54]:
# Transform 2-Dimensional array into 1-Dimensional array (i.e., column into element)
a = np.array([["A", "B", "C"], ["D", "E", "F"]], dtype=object)
np.array([''.join(col) for col in a.T], dtype=object)

array(['AD', 'BE', 'CF'], dtype=object)