# A brief summary of NumPy
<br>
<div style="opacity: 0.8; font-family: Consolas, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New; font-size: 12px; font-style: italic;">
    ────────
    for more from the author, visit
    <a href="https://github.com/hazemanwer2000">github.com/hazemanwer2000</a>.
    ────────
</div>

## Table of Contents

NumPy is a python package that provides and facilitates efficient manipulation of N-dimensional arrays.

In [1]:
import numpy as np

## Creating Arrays

In [4]:
# 1-Dimensional Array
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
# 2-Dimensional Array
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# Shape = (Rows, Columns)
a = np.array([[1, 2, 3], [4, 5, 6]])
np.shape(a)

(2, 3)

In [ ]:
# Array of zeroes
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
# Array of ones
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Array of (same) value
value = 9
np.full((3, 2), value, dtype=int)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [32]:
# Range of value(s) (i.e., start, end (exclusive), and step)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
# Linear space (i.e., start, end (inclusive), and number of value(s))
np.linspace(0, 8, 5, dtype=int)

array([0, 2, 4, 6, 8])

In [48]:
# Random integer(s) (i.e., start, end (exclusive))
np.random.randint(1, 10, size=(2, 2), dtype=int)

array([[3, 7],
       [1, 9]], dtype=int32)

In [47]:
# Random value(s) (i.e., start=0, end=1 (exclusive))
np.random.rand(2, 2)

array([[0.58692657, 0.47894508],
       [0.65121368, 0.72897931]])

## Indexing

In [ ]:
# Access element
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[0, 1]

np.int64(2)

In [ ]:
# Access row
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[1, :]

array([4, 5, 6])

In [ ]:
# Access column
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[:, 1]

array([2, 5, 8])

In [ ]:
# Slicing
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])